"use client";
import { savePropertyLease } from "@/actions/imobiliaria";
import { ArrowLeft, Save } from "lucide-react";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";

type Property = { id: string; street: string; number: string; complement?: string | null; city?: string | null; state?: string | null; monthly?: any; imob_leases?: any[] };
export function PropertyManager({ owner, properties, renters }: { owner: any; properties: Property[]; renters: any[] }) {
  const router = useRouter(); const [error, setError] = useState(""); const [saved, setSaved] = useState(""); const [pending, startTransition] = useTransition();
  function submit(formData: FormData) { setError(""); setSaved(""); startTransition(async () => { const result = await savePropertyLease(formData); if (result.error) setError(result.error); else { setSaved(String(formData.get("property_id"))); router.refresh(); } }); }
  return <div className="stack"><div className="actions"><a className="button secondary" href="/cadastros"><ArrowLeft size={15}/> Voltar para clientes</a></div>{error && <div className="notice error">{error}</div>}{saved && <div className="notice success">Imóvel atualizado.</div>}{properties.length === 0 && <div className="card"><p className="muted">Este proprietário ainda não possui imóveis importados.</p></div>}{properties.map((property) => { const lease = property.imob_leases?.[0] || {}; const monthly = property.monthly || {}; const renter = renters.find((item) => item.id === (monthly.renter_id || lease.renter_id)); return <form action={submit} className="card stack" key={property.id}><input type="hidden" name="owner_id" value={owner.id}/><input type="hidden" name="property_id" value={property.id}/><input type="hidden" name="monthly_id" value={monthly.id || ""}/><div><h2 style={{ margin: 0 }}>{property.street}, {property.number}</h2><p className="muted">Corrija os dados do imóvel e da locação.</p></div><div className="form-grid"><label className="field">Logradouro<input name="street" defaultValue={monthly.street || property.street}/></label><label className="field">Número<input name="number" defaultValue={monthly.number || property.number}/></label><label className="field">Complemento<input name="complement" defaultValue={monthly.complement || property.complement || ""}/></label><label className="field">Cidade<input name="city" defaultValue={property.city || ""}/></label><label className="field">UF<input name="state" maxLength={2} defaultValue={property.state || ""}/></label><label className="field">Contrato<input name="contract_number" defaultValue={monthly.contract_number || lease.contract_number || ""}/></label><label className="field">Aluguel mensal<input name="rent_amount" inputMode="decimal" defaultValue={monthly.rent_amount ?? ""}/></label><label className="field">Comissão mensal<input name="commission_amount" inputMode="decimal" defaultValue={monthly.commission_amount ?? ""}/></label><label className="field">Inquilino cadastrado<select name="renter_id" defaultValue={renter?.id || ""}><option value="">Selecionar pelo nome abaixo</option>{renters.map((item) => <option value={item.id} key={item.id}>{item.name}{item.document ? ` — ${item.document}` : ""}</option>)}</select></label><label className="field">Ou novo/troca de inquilino<input name="renter_name" defaultValue={renter?.name || ""}/></label><label className="field">CPF/CNPJ do inquilino<input name="renter_document" defaultValue={renter?.document || ""}/></label></div><div className="actions"><button className="button" disabled={pending}><Save size={15}/> {pending ? "Salvando..." : "Salvar imóvel e locação"}</button></div></form>; })}</div>;
}
