"use client";
import { saveOwner } from "@/actions/imobiliaria-v2";
import { Building2, Pencil, Search, X } from "lucide-react";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";

type Owner = { id: string; name: string; document?: string | null; email?: string | null; phone?: string | null; active?: boolean; imob_properties?: { id: string; street: string; number: string; complement?: string | null; active?: boolean }[] };
export function OwnerManager({ initialOwners }: { initialOwners: Owner[] }) {
  const router = useRouter(); const [owners, setOwners] = useState(initialOwners); const [editing, setEditing] = useState<Owner | null>(null); const [filter, setFilter] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const visibleOwners = useMemo(() => { const query = filter.trim().toLocaleLowerCase("pt-BR"); if (!query) return owners; return owners.filter((owner) => [owner.name, owner.document, owner.email, ...(owner.imob_properties || []).flatMap((property) => [property.street, property.number])].filter(Boolean).join(" ").toLocaleLowerCase("pt-BR").includes(query)); }, [filter, owners]);
  function edit(owner: Owner) { setEditing(owner); setError(""); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function cancel() { setEditing(null); setError(""); }
  function submit(formData: FormData) { setError(""); startTransition(async () => { const result = await saveOwner(formData); if (result.error) setError(result.error); else if (result.owner) { setOwners((current) => { const saved = result.owner as Owner; return saved.id && current.some((owner) => owner.id === saved.id) ? current.map((owner) => owner.id === saved.id ? { ...owner, ...saved } : owner) : [saved, ...current]; }); setEditing(null); router.refresh(); } }); }
  return <div className="stack"><form action={submit} className="card stack"><div className="top" style={{ marginBottom: 0 }}><div><h2 style={{ margin: 0 }}>{editing ? "Editar proprietário" : "Novo proprietário"}</h2><p className="muted">{editing ? "Atualize os dados cadastrais deste cliente." : "Cadastre o proprietário e depois vincule seus imóveis pela importação."}</p></div>{editing && <div className="actions"><a className="button secondary" href={`/cadastros/${editing.id}`}><Building2 size={15}/> Imóveis</a><button type="button" className="button secondary" onClick={cancel}><X size={15}/> Cancelar</button></div>}</div>{error && <div className="notice error">{error}</div>}<input type="hidden" name="id" value={editing?.id || ""}/><div className="form-grid"><label className="field">Nome<input name="name" required key={editing?.id || "new"} defaultValue={editing?.name || ""}/></label><label className="field">CPF/CNPJ<input name="document" key={`document-${editing?.id || "new"}`} defaultValue={editing?.document || ""}/></label><label className="field">E-mail<input name="email" type="email" key={`email-${editing?.id || "new"}`} defaultValue={editing?.email || ""}/></label><label className="field">Telefone<input name="phone" key={`phone-${editing?.id || "new"}`} defaultValue={editing?.phone || ""}/></label></div><div><button className="button" disabled={pending}>{pending ? "Salvando..." : editing ? "Salvar alterações" : "Cadastrar proprietário"}</button></div></form><section className="card"><div className="top" style={{ marginBottom: 12 }}><div><h2 style={{ margin: 0 }}>Clientes cadastrados</h2><p className="muted">{visibleOwners.length} de {owners.length} proprietário(s)</p></div><label className="field" style={{ minWidth: 260, position: "relative" }}><span className="small"><Search size={14} style={{ verticalAlign: "middle" }}/> Filtrar</span><input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Nome, CPF ou imóvel"/></label></div><div className="table-wrap"><table className="table"><thead><tr><th>Proprietário</th><th>CPF/CNPJ</th><th>Imóveis</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{visibleOwners.map((owner) => <tr key={owner.id}><td><strong>{owner.name}</strong><br/><span className="muted">{owner.email || ""}</span></td><td>{owner.document || <span className="badge pending">Pendente</span>}</td><td>{owner.imob_properties?.map((property) => `${property.street}, ${property.number}${property.complement ? ` - ${property.complement}` : ""}`).join("; ") || "—"}</td><td>{owner.active ? "Ativo" : "Inativo"}</td><td><button type="button" className="icon-button" title={`Editar ${owner.name}`} aria-label={`Editar ${owner.name}`} onClick={() => edit(owner)}><Pencil size={17}/></button></td></tr>)}</tbody></table>{visibleOwners.length === 0 && <p className="muted">Nenhum cliente encontrado para este filtro.</p>}</div></section></div>;
}
